import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const conthrax = localFont({
  src: 'font/Conthrax-SemiBold.otf',
  variable: '--font-conthrax',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${conthrax.variable}`}>
      <body>{children}</body>
    </html>
  );
}
